### ISSUE TITLE
Crash. NullPointerException. When opens the seed phase window

### ISSUE THREAD

**Issue by axosky** [tonkeeper/wallet#10]
### Bug Type

Functional

### Reproduction steps

**Case 1:**
Preconditions: Wallet not created or connected to the app
1. Open Tonkeeper
2. Tap on Connect Wallet
3. Tap on Connect Existing

**Case 2:**
1. Open Tonkeeper
2. Tap on "Settings"
3. Tap on "Security"
4. Tap on "Reset Pin"

### Actual result

App crashes when open mnemonic input screen

[seed_phrase_crash1.txt](https://github.com/tonkeeper/wallet/files/9586416/seed_phrase_crash1.txt)
[seed_phrase_crash2.txt](https://github.com/tonkeeper/wallet/files/9586417/seed_phrase_crash2.txt)

https://user-images.githubusercontent.com/101420012/190706381-026c429d-a82b-4779-8e3d-e68784029c4e.mp4

![2022-09-16 21 19 59](https://user-images.githubusercontent.com/101420012/190706390-e86262cc-f0e6-4722-ba7b-be8f330aabad.jpg)
![2](https://user-images.githubusercontent.com/101420012/190706379-ae0995b6-1321-42db-b27e-6533e2fec02d.jpg)
![1](https://user-images.githubusercontent.com/101420012/190706386-47d919ba-81a1-43e4-af3a-52ed2018a15f.jpg)

### Expected result

Mnemonic screen opens and user can enter secret key

### Suggested Severity

Medium

### Device

- Device: Xiaomi Redmi Note 8 Pro
- OS: Android 11 (RP1A.200720.011)
- Browser: None
- Version: Tonkeeper 2.6 (213)

### Additional Context

**Reproducibility: 2 of 10 on my device**

In the log, i can see that Crash occur due to Android system draw module, and also i can't reproduce issue in iOS device (iPhone), so, i think, this bug affecting only Android users.

I attached 2 device logs with crash and also the App Logs right after issue.

**Comment by MariaBit** [comment]
Hi, the issue has been registered in our system with internal # ТК-766. You will get a PR number when it will be fixed.  Thanks!
