### ISSUE TITLE
Inconsistent price shown in wallet

### ISSUE THREAD

**Issue by miroslav-tashonov** [tonkeeper/wallet#124]
### Bug Type

UI

### Reproduction steps

1. Enter wallet 2. See price movements ( its not happening always ) in the last 24h. The price is in an incline, while its shown as 20+% decline in last 24h. Also the total price is calculated badly.

Time of the screenshot: 11/11/2022 ~09:30 AM UTC +1

![image0](https://user-images.githubusercontent.com/3856771/201300662-92f90e3d-d90a-4b90-bd09-bd6c07559153.jpeg)

Stock movements in the last 24h given in the below screenshot : 
![Untitled](https://user-images.githubusercontent.com/3856771/201301938-db682fc5-84d6-4d34-8ec5-03aa7e3896ce.png)

### Actual result

When i open the wallet, sometimes bad price movement are shown in the graph 

### Expected result

Valid price movements. I hope that it is only an UI issue, otherwise it should be marked as vulnerability.

### Suggested Severity

High

### Device

Smartphone:
- Device: Iphone 11 Pro

**Comment by MariaBit** [comment]
Hi, thanks for letting us know about this problem. 
Could you check if it is still reproducible? I believe it was a temporary issue.
