### ISSUE TITLE
iOS: NFT Item not showing in transaction history

### ISSUE THREAD

**Issue by captainmarshin** [tonkeeper/wallet#14]
### Bug Type

UI

### Reproduction steps

1. Buy NFT on GetGems Marketplace
2. Scan QR code with Tonkeeper
3. Complete purchase and receive NFT item

### Actual result

Tonkeeper history shows purchase transaction and NFT received transaction, but received transaction show only Toncoin amount and not NFT item picture + NFT tag

Transactions that not shows NFT:

NFT Item: EQDLcyN7R7VdOg2aRd70cdOY-380u8I7mCYKip-cXn4CUOFs
Transaction: KGAsixWHMMkuWP71b6T7C7uROfi3HfALbmy6fae9BNQ=

NFT Item: EQA1ddurPdjweR3nVA5DA9S-_4IzhbG86wNBjBIDZk98wSvI
Transaction: GAljMpMsAf4poB6yEcbYCmKcOofKTb85XVYaxwnJ5O8=

Screenshots:
Transactions List
![photo_2022-09-17_01-26-17](https://user-images.githubusercontent.com/67394582/190825824-d91a69e1-2ecd-4a42-8425-a031ffc9716f.jpg)
NFT Item #1:
![photo_2022-09-17_01-26-20](https://user-images.githubusercontent.com/67394582/190825833-d144356f-f4a3-4b97-b8e0-e6acbd10cdc9.jpg)
NFT Item #2:
![photo_2022-09-17_01-26-22](https://user-images.githubusercontent.com/67394582/190825837-90fa91d9-7c8a-445f-b3b1-b2bff6e73222.jpg)

### Expected result

Received transaction shows NFT item and NFT tag, that user received from GetGems:

Example transaction:
NFT Item: EQDmfP8-We3VIBInYasC2BQ-UEnVkBcx3OapUgvNwFal5bNM
Transaction: KOJxaXNWwmpy0R+fFXqhX/D2yG0YCJGZecDXwRtnnsk=

Screenshots:
Transaction list:
![photo_2022-09-17_01-26-14](https://user-images.githubusercontent.com/67394582/190826889-5a49aac0-b33f-40a6-b61d-005fe5545190.jpg)
Received NFT Item:
![photo_2022-09-17_01-26-12](https://user-images.githubusercontent.com/67394582/190826885-bf2909c0-d8c5-4b26-a741-cf66a8f4ff48.jpg)

### Suggested Severity

Low

### Device

Desktop (please complete the following information):
- OS: none
- Browser: none
- Version: none

Smartphone (please complete the following information):
- Device: iPhone XR
- OS: iOS 16.0
- Browser: Safari
- Version: Safari 16

**Comment by olyaMay** [comment]
Hi, the issue has been registered in our system with internal ТК-608.
You will get a PR number when it will be fixed. Thanks!

**Comment by MariaBit** [comment]
Hi, this issue has been already fixed with another task #TK-489. 
You will see expected NFT transaction in history in the next release.
