### ISSUE TITLE
iOS: NFT is shown as Sent even if the transaction failed

### ISSUE THREAD

**Issue by captainmarshin** [tonkeeper/wallet#15]
### Bug Type

UI

### Reproduction steps

For reproduce this issue you need to get NFT, what can be transfer only from the specified marketplace.

For example, this NFT have specified marketplace in metadata from there it can be sent:
EQDe-Xg6ZvC5737oNu3mcuEslRtgF5o7LDulaeYu78LKUnF_

1. Select NFT in NFTs tab
2. Transfer NFT

### Actual result

Tonkeeper shows complete message and success transaction in Transactions list

![photo_2022-09-17_02-20-55](https://user-images.githubusercontent.com/67394582/190829984-4d8f7b25-9e83-4fc7-a799-260ba37dead3.jpg)
![photo_2022-09-17_02-21-00](https://user-images.githubusercontent.com/67394582/190829992-f97fc2e8-9ba4-45ee-ba80-cce570326a15.jpg)
![photo_2022-09-17_02-21-06](https://user-images.githubusercontent.com/67394582/190829999-e37b5567-9564-433a-9260-92c77656dd7c.jpg)

Transaction: 
https://tonscan.org/tx/dj5T64chYh84elCRDfmELGnHEeB5Gi72ld82oi_2jrg=

Transaction in NFT item:
https://tonscan.org/tx/x94w_z-WOGTNPPN_yBW5ljFogvoGF18W1pIQLfTr7Ow=

### Expected result

Tonkeeper stops transaction and shows message about NFT transfer requirements.

### Suggested Severity

Low

### Device

Smartphone (please complete the following information):
- Device: iPhone XR
- OS: 16.0
- Browser: Safari
- Version: 16

### Additional Context

NFT in example have option to transfer only from tonmarket website. Thanks to @krimon to explain this.
This issue have connections to this issue: https://github.com/getgems-io/issues/issues/8

**Comment by DeFiTON** [comment]
This is a "bug contract" mint of this collection

**Comment by olyaMay** [comment]
As @DeFiTON said, this is really about this NFT contract bug. You can send this NFT only from TonMarket.
