### ISSUE TITLE
Extra transaction "Unknown" in tonkeeper list

### ISSUE THREAD

**Issue by isopen** [tonkeeper/wallet#160]
### Bug Type

UI/UX

### Reproduction steps

1. I just played some TON Play games and won a real NFT (Accidentally lucky. Won NFT with Tongochi)
2. NFT successfully received after participating in the lottery by TON Play.
3. Transaction "Unknown: Unknown" appeared in the list above the NFT transaction.

### Actual result

https://user-images.githubusercontent.com/7373292/205494987-c49e50ab-1082-4ea0-82a8-715de78e555b.mp4

### Expected result

Fix an opaque transaction "Unknown: Unknown"

### Suggested Severity

High

### Device

Smartphone (please complete the following information):
Samsung A71
Android 12
Tonkeeper 2.7.4

**Comment by Dobrinya** [comment]
I have the same trouble - I bought on the stock exchange ton and don see it on balance. Transaction is Unknown Unknown

Device
Xiaomi Redmi Note 11 PRO 5G
MIUI 13.0.3
Android 12 SKQ1.211006.001
Tonkeeper 2.8.0

**Comment by mr-tron** [comment]
Thank you. We know about the issue. It's not something dangerous and we are working on big update which will fix all problems with "Unknown" actions in history.
