### ISSUE TITLE
Android: User can't copy recovery phrases

### ISSUE THREAD

**Issue by vegancat** [tonkeeper/wallet#17]
### Bug Type

UX

### Reproduction steps

Case 1:
1- Open the newly installed app
2- Create a new wallet
3- Phrases would be shown but no way to copy them at once

Case 2:
1- Open the app
2- Open "settings"
3- Open "Recovery phrase"
4- Phrases would be shown but no way to copy them at once

### Actual result

Phrases would be shown, but no way to copy them at once

![case_1](https://user-images.githubusercontent.com/44384370/190830889-6843bf4b-b325-4490-997c-f43231974946.jpg)
![case_2](https://user-images.githubusercontent.com/44384370/190830968-f8f51ddb-8c3b-4550-8c72-f5ca03da7bdb.jpg)

### Expected result

Users should be able to copy all 24 phrases to store them in a secure place. When the user copies all their 24 phrases and pastes them into the "import existing wallet" part, the app splits those up and fills 24 inputs with phrases.

So to remove this inconsistency in UX, it's suggested to provide users with "copy phrases" button

### Suggested Severity

Low

### Device

Smartphone (please complete the following information):
- Device: [e.g. J7 Pro]
- OS: [e.g. Android 9]
- Browser [tonkeeper app]
- Version [e.g. 2.6]

**Comment by olyaMay** [comment]
Hi! We don't give ability to copy recovery phrase because it is not secure to keep it in the clipboard. Also I recommend to you don’t taking screenshots with the recovery phrase.
