### ISSUE TITLE
Android: could not encrypt the value for SecureStore

### ISSUE THREAD

**Issue by data-will-be-here** [tonkeeper/wallet#18]
### Bug Type

Functional

### Reproduction steps

If you add another fingerprint to the system after installing tonkeeper, tonkepeer will disable the use of fingerprint and will not allow you to enable this feature again.

1. Click settings -> safety
2. Click enable fingerprint and enter pin
3. Get'could not encrypt the value for SecureStore'

### Actual result

Error "could not encrypt the value for SecureStore"

### Expected result

Function should work independently of the user's actions in the system, as in any other application.  The user should not be forced to reinstall the application and re-import the security settings.

### Suggested Severity

Medium

### Device

- Device: Redmi Note 11 Pro
- OS: Android
- Version 11

### Additional Context

https://user-images.githubusercontent.com/85282394/190843197-e50b0da0-f1c0-4bff-83e1-b0c71f9394ff.mp4

**Comment by MariaBit** [comment]
Hi, the issue has been already fixed and will be available in the next release. (Internal bug # TK-393.)
Thanks!
