### ISSUE TITLE
In-App Browser not support .ton domains

### ISSUE THREAD

**Issue by captainmarshin** [tonkeeper/wallet#204]
### Bug Type

Other

### Reproduction steps

1. Open Browser Tab
2. Type http://foundation.ton or any .ton domain with website on it.

### Actual result

<img src="https://user-images.githubusercontent.com/67394582/210057456-9c63a1fa-b902-4ed8-b825-3439d86a17c1.jpeg" width="150" height="auto">

### Expected result

NSURLErrorDomain

### Suggested Severity

Low

### Device

- Device: iPhone XR
- OS: iOS 16.2
- Tonkeeper App
- Version 2.8.0 (App Store)

**Comment by olyaMay** [comment]
Hi, the issue has been registered in our system with internal #TK-1128. You will get a PR number when it will be fixed. Thanks!
