### ISSUE TITLE
iOS: Flashlight is not turning off when QR scanner is closed

### ISSUE THREAD

**Issue by julialips** [tonkeeper/wallet#21]
### Bug Type

Functional

### Reproduction steps

1. Open Tonkeeper 
2. Log in to your wallet
3. Open 'Send' flow
4. Click the QR scanner button in the wallet address field -> the scanner opens
5. Click the flashlight button 
    **Actual result:** the light is on.
6. Swipe down/close the scanner 

https://user-images.githubusercontent.com/45575431/190926454-97e22eb1-59e7-40ab-b775-283f25ca3bb0.mp4

### Actual result

The 'Wallet' tab is opened. The light is still on.

### Expected result

When the scanner is closed, the flashlight turns off.

### Suggested Severity

Medium

### Device

- Device: iPhone 11
- OS: 14.3

### Additional Context

When flashlight is on and a user going and returning from background - the light is off, but the button state is - pressed and the camera is freezing.

https://user-images.githubusercontent.com/45575431/190868917-092dbd43-c510-4284-a652-56a33b8c9e7b.MP4

**Comment by olyaMay** [comment]
Hi, the issue have been registered in our system with internal TK-794. You will get a PR number when it will be fixed. Thanks!
