### ISSUE TITLE
Jetton image is not loaded

### ISSUE THREAD

**Issue by data-will-be-here** [tonkeeper/wallet#24]
### Bug Type

UI

### Reproduction steps

1. Mint jetton by ton whales tool, for ex. EQCzUQNb0sEwvRO6MTSCHhHQVjwntJY8oWqAVNrN1bZw3iUb
2. See it in tonkeeper

### Actual result

Image is not loaded.
![image](https://user-images.githubusercontent.com/85282394/190888502-57aaebd6-4a80-4c0e-9005-321db9694fca.png)
![image](https://user-images.githubusercontent.com/85282394/190888515-4bcfc914-2b62-4099-b6f3-cb333d120899.png)

### Expected result

https://tonscan.org/jetton/EQCzUQNb0sEwvRO6MTSCHhHQVjwntJY8oWqAVNrN1bZw3iUb
![image](https://user-images.githubusercontent.com/85282394/190888518-67d9e65b-672c-4032-abed-72243e11160c.png)

### Suggested Severity

Low

### Device

Desktop (please complete the following information):
- OS: android
- Version: 11

**Comment by olyaMay** [comment]
Hi, the issue have been registered in our system with internal TK-798. You will get a PR number when it will be fixed. Thanks!

**Comment by olyaMay** [comment]
Image source url points to IPFS network. It has availability problems based on IPFS architecture. You can add more seeders for source url (or ask about this Ton Whales team). 
Some services (like tonscan) has this image in their caches by unknown reasons. Maybe they caught  image before availability  problems.  We can't manually manage images for every jetton.
