### ISSUE TITLE
"Failed to calculate fee" when using Jetton transfer payment url

### ISSUE THREAD

**Issue by arterialist** [tonkeeper/wallet#240]
### Bug Type

UI

### Reproduction steps

1. Craft a Jetton-transfer payment url (example: https://app.tonkeeper.com/transfer/EQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N?jetton=EQD0vdSA_NedR9uvbgN9EikRX-suesDxGeFg69XQMavfLqIw&amount=1000&fee-amount=1000&forward-amount=1000)
2. Navigate to it

### Actual result

"? TON" is displayed in the "Fee" section of the bottom sheet and "Failed to calculate fee" toast appears

![image](https://user-images.githubusercontent.com/37044735/216386482-14dd569a-66a2-46e6-adbe-a46291ff4b30.png)

### Expected result

No "Failed to calculate fee" toast and correctly calculated fee in the bottom sheet

### Suggested Severity

Low

### Device

Smartphone (please complete the following information):
- Device: Pixel 6
- OS: Android 13.0
- Browser: no browser
- Version: 2.9.0 (268)

**Comment by olyaMay** [comment]
Fixed.
