### ISSUE TITLE
Unable to send NFT to another wallet address

### ISSUE THREAD

**Issue by extenderness** [tonkeeper/wallet#241]
### Bug Type

Functional

### Reproduction steps

1. Open the app
2. Select NFT tab, tap on NFT item (telegram @ username)
3. Press blue button [Отправить NFT]
4. Enter destination wallet-address or .ton domain name (same result)
5. .ton domain successfuly validated
6. Press [Продолжить]
7. Nothing happens
8. Goto 6.
...
∞-1. Press top-right [X] button to close the window-with-[Продолжить]-button.
∞. App goes to the next confirmation step with [Отмена] and [Подтвердить] buttons., instead of canceling NFT sending process.

### Actual result

Nothing happens on step 6. NFT is not sended.
"Отправить NFT" window stay open. No errors, no extra messages shown.
Button [Продолжить] does nothing. No visual response.

### Expected result

After reproduction step
6. Press [Продолжить]
app must show the next confirmation step with [Отмена] and [Подтвердить] buttons.

Pressing [X] on step 6. must cancel NFT sending process.

### Suggested Severity

Medium

### Device

Smartphone:
- Device: Xiaomi Mi 6
- OS: Android 9, MIUI Global 11.0.6
- App version: Tonkeeper 2.9.0, com.ton_keeper (from Play Market)

### Additional Context

Device is not rooted.
Developer mode is Enabled OR  Developer mode is Disabled (both states applied)

**Comment by MariaBit** [comment]
Hi, the issue has been registered in our system with internal #TK-885. You will get PR number when it will be fixed. Thanks!

**Comment by MariaBit** [comment]
The issue has been fixed in PR #666.
