### ISSUE TITLE
Add forced language selection option

### ISSUE THREAD

**Issue by extenderness** [tonkeeper/wallet#242]
### Bug Type

UX

### Reproduction steps

1. Go to app's Настройки.
2. Be disappointed not having language selection option.

### Actual result

Be disappointed not having language selection option.

### Expected result

Please add language selection option.

### Suggested Severity

Low

### Device

Smartphone
- Device: Xiaomi Mi 6
- App version: Tonkeeper 2.9.0, com.ton_keeper (from Play Market)

**Comment by olyaMay** [comment]
Hi. Now you can change language in the dev menu. For dev menu opening you need to tap 5 times on app version.
