### ISSUE TITLE
Insecure form of private key storage

### ISSUE THREAD

**Issue by XaartlonDreezey** [tonkeeper/wallet#243]
### Bug Type

Security

### Reproduction steps

1. Check code from File 'main.ts' --- database 
2. Storing private keys in plain text: The private keys are stored in plain text format which is a security vulnerability. If the device is hacked or the data is leaked, the private keys can be used to access the user's funds. In this file, private keys are stored in plain text in the 'privateKey' property of the Wallet model. This is a potential security vulnerability, as anyone with access to this information can easily use the private key to access and manipulate the corresponding wallet.

### Actual result

No protection of production data (critical infrastructure). We need to exclude access to any keys, even if they are on the device. At any time, the device can be captured.

### Expected result

We tracked the location of the private key and know where the system stores important data. This is a breach in terms of data security and privacy.

### Suggested Severity

High

### Device

Desktop (please complete the following information):
- Windows
- Version 11 

### Additional Context

The vulnerability is in the code of the file. During code review, an unsafe segment was identified.

**Comment by bogoslavskiy** [comment]
We do not store a private key in AsyncStorage as plain text. AsyncStorage needed for ancillary data.
