### ISSUE TITLE
In-app browser doesn't allow web apps to copy text to clipboard

### ISSUE THREAD

**Issue by arterialist** [tonkeeper/wallet#247]
### Bug Type

Functional

### Reproduction steps

1. create a simple html page that invokes `navigator.clipboard.writeText("test")` on click
2. open this web page in Tonkeeper's in-app browser
3. click on the element

### Actual result

`NotAllowedError: Write permission denied.` unhandled exception is thrown

### Expected result

Text is copied to the clipboard

### Suggested Severity

Medium

### Device

Smartphone (please complete the following information):
- Device: Pixel 6
- OS: Android 13
- Browser: in-app (Chrome WebView)
- Version: 2.9.0 (268)

### Additional Context

Possible ways to resolve this:
https://stackoverflow.com/questions/61243646/clipboard-api-call-throws-notallowederror-without-invoking-onpermissionrequest

**Comment by arterialist** [comment]
This bug also affects TonConnect's "Copy address" button provided by TonConnectButton component, thus making it useless inside the In-app browser.

**Comment by olyaMay** [comment]
Fixed.
