### ISSUE TITLE
Feature request: add support for custom plugins

### ISSUE THREAD

**Issue by ProgramCrafter** [tonkeeper/wallet#256]
Hello!
Currently, only standard subscription contract can be added via deeplinks.
I want there to be a way to add any plugin to wallet via QR/TON Connect 2, given plugin's stateInit, workchain and amount of funds to deploy it.

For safety, an additional option could be added into menu, and during adding plugin there could be a warning "WARNING! THIS PLUGIN CAN TAKE ALL YOUR FUNDS!" and link to disassembler with contract's code.

**Comment by ProgramCrafter** [comment]
The use case is linked to my project [Ratelance](https://github.com/ProgramCrafter/ratelance/).

The platform needs to take stakes from freelancers because otherwise they could lock job poster's money in multisig smart contract forever, and now they'll lock their own money as well.

However, taking stake at the very beginning is not very nice: what if job poster does not accept offer? That's why it's needed to be able to withdraw money at the moment when job poster accepts the offer. This is exactly what v4 wallet plugins offer.

**Comment by olyaMay** [comment]
Hi. You can ask Ton Connect team about this feature. https://github.com/ton-connect
