### ISSUE TITLE
Android: "Failed to get addresses balances" if internet off

### ISSUE THREAD

**Issue by ApplY3D** [tonkeeper/wallet#258]
### Bug Type

Security

### Reproduction steps

1. Turn off wifi
2. Import wallet with seed 

### Actual result

error "Failed to get addresses balances"

### Expected result

wallet imported

### Suggested Severity

Vulnerability

### Device

Smartphone (please complete the following information):
- Device: any
- OS: Android

**Comment by olyaMay** [comment]
Hi. Thanks for your feedback. It is ok flow when you can't import existing wallet without internet connection because application couldn't know ton/tonkens/nfts balances without internet connection.

**Comment by ApplY3D** [comment]
It might be decrypted without internet and then update balances after reconnect. I just want to securely import wallet from seed. I don't need balances on that step.
