### ISSUE TITLE
iOS: No way to move back, on the 'Create new wallet' flow

### ISSUE THREAD

**Issue by julialips** [tonkeeper/wallet#26]
### Bug Type

UX

### Reproduction steps

1.Open Tonkeeper
2. Click 'Set up wallet'
3. Choose 'Create new wallet'
4. Opens the screen 'Grab a pen and a piece of paper'
5. Try to return to the main first app screen

### Actual result

Impossible to return to the main home screen, when opening creating new wallet flow.
You should kill the app in recent and restart again
![13](https://user-images.githubusercontent.com/45575431/190894189-472a80a9-684c-47b5-a30f-eb2d8c619bd3.jpg)

### Expected result

Users should be able to move in the app as they want. 
Every screen should have arrow button to return back or some button to return to the main screen.

### Suggested Severity

High

### Device

    Device: iPhone 11
    OS: 14.3

**Comment by olyaMay** [comment]
Hi. At the moment wallet has been created. This is necessary in order to avoid accidental returns or resets. We will think about how to improve the creation flow.
