### ISSUE TITLE
Bug: In-app Browser makes URL lowercase

### ISSUE THREAD

**Issue by arterialist** [tonkeeper/wallet#270]
### Bug Type

Functional

### Reproduction steps

1. Open any link that has upper-case symbols in it
2. Page's location becomes lowercase

https://user-images.githubusercontent.com/37044735/224138787-a4c3fe3f-2287-4d15-85f2-910024df2a23.mp4

### Actual result

Entire webpage URL is converted to lowercase

### Expected result

Webpage URL is kept untouched

### Suggested Severity

Medium

### Device

Smartphone (please complete the following information):
- Device: Google Pixel 6
- OS: Android 13
- Browser: In-app
- Version 2.9.0

**Comment by olyaMay** [comment]
Hi. This issue was fixed in 3.4.4 release.
