### ISSUE TITLE
NFT button missing after app update via apk from site https://tonkeeper.com/

### ISSUE THREAD

**Issue by isopen** [tonkeeper/wallet#28]
### Bug Type

UI/UX

### Reproduction steps

<img src="https://user-images.githubusercontent.com/7373292/190921485-c53af934-c5a8-4e8a-83ee-b4cba6f94172.png" width="30%" /> <img src="https://user-images.githubusercontent.com/7373292/190921511-75e2fc7f-4bc9-46e6-af45-2a1c82742527.png" width="30%" /> <img src="https://user-images.githubusercontent.com/7373292/190921802-b927486a-c180-4937-8583-021a9050a776.png" width="30%" />

### Actual result

NFT button missing after update via apk.

### Expected result

NFT button present after update via apk

### Suggested Severity

Critical

### Device

Desktop (please complete the following information):
- OS: Android 12
- Browser Android 12
- Version 12
- Tonkeeper Версия 2.6

**Comment by olyaMay** [comment]
Hi. NFT button now displays only in cases when you have NFTs on your balance.

**Comment by isopen** [comment]
Hi. NFT button in Tonkeeper

**Comment by isopen** [comment]
She's not on the screen. This is a bug

**Comment by isopen** [comment]
Your condition doesn't always work. Because I have never had an NFT on my balance sheet, but I did have an NFT button.

**Comment by isopen** [comment]
Why was the report closed?

**Comment by isopen** [comment]
@olyaMay Why was the report closed?

**Comment by MariaBit** [comment]
Hello!

At the moment NFT button should be visible only when you have at least one NFT on your balance.
Because of that we closed this issue (#28).

However, you filed another bug https://github.com/tonkeeper/wallet/issues/51 and it seems valid. 
We are investigating it and will be back with an answer why NFT button became visible when there is no NFT.

Thanks!

**Comment by isopen** [comment]
The NFT button may not appear in one more case. When integration cannot be reached. Even if the user has NFT.
