### ISSUE TITLE
Does not process testnet deployment transaction with an unknown error - how to debug?

### ISSUE THREAD

**Issue by vitalif** [tonkeeper/wallet#284]
### Bug Type

Functional

### Reproduction steps

Hi. When I show a QR code with a testnet deployment transaction and scan it with Tonkeeper (switched to testnet) it shows transaction details, says "An error happened" (without any detail) in a popup message and doesn't allow to process the transaction. The same transaction is processed fine with Tonhub when requested through its remote API.

How to at least find the cause or any details of the problem?

![txn](https://user-images.githubusercontent.com/945339/226165113-9e1ab312-a811-47d5-9c25-3f46c5bee97f.png)

### Actual result

Transaction is not processed with unknown error "Произошла ошибка"

### Expected result

Should be processed

### Suggested Severity

High

### Device

Smartphone:
- Device: Mi 9
- OS: Android 9
- Tonkeeper 2.9.0

**Comment by olyaMay** [comment]
Hi. Thank you for your feedback. There are some mistakes in our documentation. "type": "deploy" has never worked and it was changed to  "type": "sign-raw-payload".
