### ISSUE TITLE
iOS: It is possible to create send transactions for the future

### ISSUE THREAD

**Issue by julialips** [tonkeeper/wallet#29]
### Bug Type

Functional

### Reproduction steps

1. Open Tonkeeper app
2. Log in to your wallet or create new one
3. Go to device settings (Settings - General - Data & Time)
4. Switch off 'Set Automatically' switcher
5. Set manually the date: 2 day forward 
6. Open the app
7. Make send transaction
Actual result: Pending transaction is created and displayed on the UI. But the funds were successfully sent.
8. Return device settings, switch on 'Set Automatically' switcher
9. Return to the app

### Actual result

There is pending transactions for the future date.

<img width="250" alt="image_2022-09-18_23-37-50" src="https://user-images.githubusercontent.com/45575431/190928682-160504d9-8960-4fba-9906-78f6ef804606.png">

### Expected result

Some ways:
1. You have good check for 'Set automatically' feature.
This check may be for every send transactions, which will not allow to proceed this case, if the setting is off.
2. As transactions really were send, I guess, it is only UI bug. 
You may clear pending transactions from the future pending list, if these transactions were send, may be some check by transaction id may help.

### Suggested Severity

High

### Device

Device: iPhone 11
OS: 14.3

**Comment by MariaBit** [comment]
Hi, the issue has been already fixed and will be available in the next release. 

For the specified case, the incorrect behavior for pending transaction has been fixed. And we also added a warning message to inform users that they need to turn on automatic time and date on their device if it is turned off.

Thanks!
