### ISSUE TITLE
Integrate Italian

### ISSUE THREAD

**Issue by RubensRainelli** [tonkeeper/wallet#297]
### Bug Type

Localization

### Reproduction steps

Missing italian language

### Actual result

Missing italian language

### Expected result

Accepting PR: [https://github.com/tonkeeper/wallet/pull/293](https://github.com/tonkeeper/wallet/pull/293) will integrate Italian Language

### Suggested Severity

Low

### Device

All

### Additional Context

For the PR:
[https://github.com/tonkeeper/wallet/pull/293](https://github.com/tonkeeper/wallet/pull/293)

**Comment by olyaMay** [comment]
Hi. PR #239 has already been merged.
