### ISSUE TITLE
iOS: Impossible to scan QR code using native camera

### ISSUE THREAD

**Issue by julialips** [tonkeeper/wallet#30]
### Bug Type

Functional

### Reproduction steps

Precondition: Tonkeeper app is installed

Steps: 
1. Open native phone camera
2. Scan some Tonkeeper QR code to receive funds

### Actual result

A link appears that opens а browser.

### Expected result

If a user is logged in - send opens with prefilled address.
If a user is not logged in - the main app screen opens.

### Suggested Severity

Low

### Device

Device: iPhone 11
OS: 14.3

### Additional Context

It is like feature request :)

**Comment by olyaMay** [comment]
Hi, the issue have been registered in our system with internal TK-765. You will get a PR number when it will be fixed. Thanks!

**Comment by olyaMay** [comment]
Issue have been fixed in the PR #66 
It will be available for users in the next app release
