### ISSUE TITLE
iOS: No alert about no internet connection

### ISSUE THREAD

**Issue by julialips** [tonkeeper/wallet#31]
### Bug Type

UX

### Reproduction steps

1. Open Tonkeeper app
2. Switch off the Internet on your phone
3. Open Send flow and try to send, or try to Buy TON 

### Actual result

For Send flow, will be infinite loader at the send button.
For Buy flow, Neocrypto opens with 404 error, and Mercuryo opens with infinite loader. 

![photo_2022-09-19_01-54-05](https://user-images.githubusercontent.com/45575431/190931721-85403fdf-8a74-4fe0-b873-50a9b4344025.jpg)
![photo_2022-09-19_01-54-08](https://user-images.githubusercontent.com/45575431/190931723-fe008675-d16f-4728-9553-c1cd3bc32528.jpg)

### Expected result

Some alert about no internet connection appears when choosing buy crypto provider and 'Continue' button at the send flow. 

### Suggested Severity

Medium

### Device

Device: iPhone 11
OS: 14.3

**Comment by archazriel** [comment]
On Android (main view) after dropping connection and reconnecting loader not disappearing and it is not possible to refresh data.

https://user-images.githubusercontent.com/108552925/190932396-c89856f9-c0ca-41d2-8e43-0059a47951ad.mp4

Device: Samsung S21
Android: 12

**Comment by MariaBit** [comment]
Hi, Julia! 
The issue has been registered in our system with internal # ТК-791. 
You will get a PR number when it will be fixed. Thanks!

**Comment by olyaMay** [comment]
Mostly fixed.
