### ISSUE TITLE
Unknown record in my transactions

### ISSUE THREAD

**Issue by mhbdev** [tonkeeper/wallet#312]
### Bug Type

Functional

### Reproduction steps

1. Place a bid lower than minimum bid on a dns auction
2. Place a new bid with the exact same amount as minimum bid amount of the domain you tried to bid.

### Actual result

![Screenshot_20230405_045701_Tonkeeper](https://user-images.githubusercontent.com/53684884/229958003-3709aff4-6abd-49cf-8460-22c57b42f14c.jpg)

### Expected result

I expected that the previous bid should be replaced by the new one and if not I should not be seeing this unknown tile in my transactions list.

### Suggested Severity

Low

### Device

Smartphone (please complete the following information):
- Device: Galaxy S21 Ultra
- OS: Android
- Version: Android 13

**Comment by olyaMay** [comment]
Hi. Thank you for your report. Sometimes unknown transactions appears, but we are doing our best to solve this problem.
