### ISSUE TITLE
Android: Tonkeeper has no their native app icon

### ISSUE THREAD

**Issue by julialips** [tonkeeper/wallet#32]
### Bug Type

UI

### Reproduction steps

1. Download Tonkeeper app from Play Market

### Actual result

The app icon looks like an android default icon for apk.

![photo_2022-09-19_02-11-38](https://user-images.githubusercontent.com/45575431/190932217-d7f71d25-5ce6-4211-ad37-7e6dcc11f914.jpg)

### Expected result

Should be native icon 

### Suggested Severity

High

### Device

- Device: Huawei P10 lite
- OS: 7.0

**Comment by MariaBit** [comment]
Hi, the issue has been registered in our system with internal # ТК-769. 
You will get a PR number when it will be fixed. Thanks!

**Comment by extenderness** [comment]
Same bug: default android icon for apk.
App version: 2.9.0
Device: Xiaomi Redmi 4A
Android 7.1.2, MIUI Global 9.5
