### ISSUE TITLE
NFT description does not allow to click on links, or copy data

### ISSUE THREAD

**Issue by kazeens** [tonkeeper/wallet#323]
### Bug Type

UX

### Reproduction steps

Hello, guys.
I have a suggestion to the NFT section.
There are some NFTs that have links in theirs description.

Would it be possible to make them clickable(or copyable)?
I guess it might really facilitate UX greatly. 
Thanks

![telegram-cloud-photo-size-2-5318875353655133075-y](https://user-images.githubusercontent.com/31125887/232154918-71266d05-43d8-48d2-9a98-d9fdf7dd1c55.jpg)

### Actual result

Links in NFT description are not copyable

### Expected result

Links in NFT description are clickable or copyable

### Suggested Severity

High

### Device

Desktop (please complete the following information):

Smartphone (please complete the following information):

**Comment by kazeens** [comment]
I am making a collectibles in TON so this really matters, cause the main purpose of the NFTs in my project is to link to some digital resources. 
So you I suppose users have to do it effortlessly

**Comment by olyaMay** [comment]
Hi. Thank you for you suggestion. We don't plan adding this functional because it can be a big possibility for scam NFTs.
