### ISSUE TITLE
Redundant message in section "Безопасность"

### ISSUE THREAD

**Issue by isopen** [tonkeeper/wallet#33]
### Bug Type

UI

### Reproduction steps

https://user-images.githubusercontent.com/7373292/191021908-364770be-7056-452c-a51a-ab6ffaa64953.mp4

### Actual result

1. Go to section "Безопасность"
2. Click "Использовать распознавание лица"
3. Click icon X
4. An information message appears "Доступ запрещён"

In the case of a button "Показать секретный ключ" likewise

### Expected result

Message "Доступ запрещён" unnecessary. I suggest removing it.

### Suggested Severity

Low

### Device

Smartphone (please complete the following information):
- Device: Samsung A71
- OS: Android 12

**Comment by MariaBit** [comment]
Hi, the issue has been registered in our system with internal # ТК-770. 
You will get a PR number when it will be fixed. Thanks!
