### ISSUE TITLE
After relogin, the "Основная валюта" of the wallet is reset

### ISSUE THREAD

**Issue by isopen** [tonkeeper/wallet#34]
### Bug Type

UX

### Reproduction steps

<img src="https://user-images.githubusercontent.com/7373292/191040752-2a6d70e4-3d58-4c76-8c82-eebf8cfd36d6.png" width="30%" />

### Actual result

1. login in wallet
2. go to settings
3. select a base currency other than the default currency
4. log out
5. login in wallet
6. go to settings
7. the currency was reset to the default currency, and not the one that was selected during the last login

### Expected result

Keep non-confidential settings

### Suggested Severity

Low

### Device

Smartphone (please complete the following information):
- Device: Samsung A71
- OS: Android 12

**Comment by olyaMay** [comment]
Hi! It is ok to reset user settings after log out. Caching settings is not good in this case, so we are trying to avoid it.
