### ISSUE TITLE
Missing features: multi-accounts and proxy

### ISSUE THREAD

**Issue by alfredonodo** [tonkeeper/wallet#350]
Hi,
after the addition of the staking functionality, to be a complete wallet it lacks the functionality to handle multi-accounts and the proxy to access TON Services (TON Sites, Storage, Apps).
When are you planning to add these functionalities that are present in some wallets such as MyTONWallet and OpenMask?
Thank you

**Comment by master88wi** [comment]
+1
pls add multi acc support + proxy

**Comment by olyaMay** [comment]
Hi. Thank you! We have some plans, but there are no dates at the moment.

**Comment by master88wi** [comment]
> Hi. Thank you! We have some plans, but there are no dates at the moment.

???
