### ISSUE TITLE
When switching to another wallet, tx history does not update

### ISSUE THREAD

**Issue by Karamelka01** [tonkeeper/wallet#37]
### Bug Type

UI

### Reproduction steps

![IMG_20220919_075852](https://user-images.githubusercontent.com/113877905/191046093-149507cd-a441-41b3-be8d-721774fe87d6.jpg)
![IMG_20220919_074410](https://user-images.githubusercontent.com/113877905/191046107-1ceece9b-aa01-4274-9fda-0182ab756589.jpg)
![IMG_20220919_074343](https://user-images.githubusercontent.com/113877905/191046116-fc815e50-e39d-47be-ba5a-81627b700b7b.jpg)

### Actual result

 При переходе на другой кошель(в скринах) растраты остаются + иногда ошибка вылазит

### Expected result

Исправление ошибки

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):

Smartphone (please complete the following information):

### Additional Context

Соединение хорошее!

**Comment by olyaMay** [comment]
Hi. What do you mean about changing wallet? Do you log out from one wallet and log in to another? Or maybe you just changing the active address?

**Comment by oleganza** [comment]
Насколько я понимаю, баг в том, что при смене кошелька история транзакций не обновляется, а остается со старого кошелька.

**Comment by oleganza** [comment]
Есть баг на это: TK-632

**Comment by Karamelka01** [comment]
Да, именно это
--
Отправлено из Mail.ru для Android воскресенье, 25 сентября 2022г., 12:10 +03:00 от Oleg Andreev  ***@***.*** :

**Comment by olyaMay** [comment]
Fixed.
