### ISSUE TITLE
Incorrect display and calculation of token transaction amount

### ISSUE THREAD

**Issue by teplulya** [tonkeeper/wallet#38]
### Bug Type

Functional

### Reproduction steps

1. Через сайт https://tonwhales.com/ создала жетон **TestCoin** c symbol **TEST** и decimal полем равным 3 (его адрес  `EQBRwbga1sZgx_aYHJrcYV5ySAwy_ensyRxSVqxAwe6YCKG8`). Отправила 2 млн. TEST монет на свой кошелек, они корректно отобразились в кошельке TonHub.
3. Зашла в этот же кошелек через Tonkeeper, но там вместо 2 млн. отобразились 2 монетки (и в балансе, и в транзакциях), а также не отобразилось изображение жетона.
4. Решила проверить исходящую транзакцию с Tonkeeper, перевела на другой Tonhub кошелек 0.5 TEST монет, и, как и ожидала, по факту перевелось 500 000 монет.
Думаю, проблема в том, что Tonkeeper по какой-то причине не смог прочитать метаданные о жетоне и решил, что там стандартное значение decimal – 9, и разрешил отправить такую транзакцию. Вероятно, в таком случае, нужно или не отображать вообще такой жетон, или не давать отправлять транзакции по нему, пока metadata не будет получена.
![тонкипер](https://user-images.githubusercontent.com/112620594/191074122-c00a3652-4045-475f-8c4b-f54ad4194e3b.jpg)
![тонкипер2](https://user-images.githubusercontent.com/112620594/191074165-b7a4b1c9-afdc-4b27-90c3-36d93a3fc42c.jpg)

### Actual result

Ожидаемый и фактический результат для сохранения логики воспроизведения описала в шагах выше.

### Expected result

Ожидаемый и фактический результат для сохранения логики воспроизведения описала в шагах выше.

### Suggested Severity

Critical

### Device

Smartphone
- Device: iPhone 13 mini
- OS: iOS 15.6
- Browser: safari

**Comment by olyaMay** [comment]
Hi. Thank you. We accepted this bug. It number will be TK-761

**Comment by olyaMay** [comment]
Bug has been fixed. Can you reproduce it please?
