### ISSUE TITLE
Android App - second payment window issue

### ISSUE THREAD

**Issue by JohnnyGoGoGo** [tonkeeper/wallet#4]
### Bug Type

Functional

### Reproduction steps

1. Follow the link to pay and unlock Tonkeeper
2. Revisit the payment link

### Actual result

When you reuse a link like https://app.tonkeeper.com/transfer/..., a second payment window opens. Because of what, having paid once, you can accidentally pay a second time if you have time to click on the button before it disappears. It shouldn't exist at all.
![Screenshot_20220916_170243](https://user-images.githubusercontent.com/94261724/190657387-91a085a4-e18c-4507-92a0-c3cbcf3c0092.jpg)

### Expected result

The second payment window should not open before the first one has closed.

### Suggested Severity

Low

### Device

Device: Samsung S10
OS: Android 12
Tonkeeper Version: 2.6

**Comment by MariaBit** [comment]
Hi, the issue has been registered in our system with internal # ТК-771. 
You will get a PR number when it will be fixed. Thanks!

**Comment by MariaBit** [comment]
Hello! The issue has been fixed and will be available in next release. (PR #259 )
