### ISSUE TITLE
Tonkeeper crushes after opening wrong site

### ISSUE THREAD

**Issue by braveltd** [tonkeeper/wallet#409]
### Bug Type

Functional

### Reproduction steps

1. Open TonKeeper
2. Connect to any tonconnect app with broken manifest (for example this - https://raw.githubusercontent.com/ton-defi-org/tonconnect-manifest-temp/main/tonconnect-manifest.json)
```json
{
  "url": "",
  "name": "TON Template Project",
  "iconUrl": ""
}
```
3. Open "Browser" (3d) Tab and click on square named TON Template Project (in my case)

### Actual result

When action is done - tonkeeper show's white screen for a moment - than crushes.

### Expected result

Idk, probably don't show this square since begging?

### Suggested Severity

Vulnerability

### Device

Smartphone (please complete the following information):
- Device: iPhone 0 Pro Max S+ Ultra
- OS: iOS 16.4.1
- Browser BRAVE :)
- Version 3.2.0

### Additional Context

да кароче все просто, что-то в коде происходит когда он не может открыть ссылку, тупо потому что ссылка пустая.

модель телефона не настоящая, я просто анонимность люблю)

**Comment by olyaMay** [comment]
Won't fix.
