### ISSUE TITLE
TONKeeper_баг с версиями кошельков

### ISSUE THREAD

**Issue by TONFOND** [tonkeeper/wallet#41]
### Bug Type

UX

### Reproduction steps
1. войти в раздел "Настройки"
2. выбрать "Текущий адрес"
3. поменять адрес кошелька

https://user-images.githubusercontent.com/113825222/191134141-6131bf28-4815-4709-8c31-31bb340b70dd.mov

[LOG ошибки_1.docx](https://github.com/tonkeeper/wallet/files/9602844/LOG._1.docx)

### Actual result

Переключение между версиями кошелька в приложении на IPhone XS версия ПО 15.2.1.
вызывает сообщение об ошибке. Продолжать пользоваться приложением невозможно. После перезапуска приложения загружается уже новый кошелек. Ошибка повторяется при каждом подобном действии. Видео шагов инициирующих ошибку приложено, как и лог ошибки.

### Expected result

Ошибка не должна проявляться, приложение должно продолжать работать.

### Suggested Severity

Medium

### Device

Smartphone (please complete the following information):
- Device: IPhone XS
- OS: IOs 15.2.1.
- Browser APP
- Version 2.6

**Comment by olyaMay** [comment]
Hi, the issue have been registered in our system with internal TK-774. You will get a PR number when it will be fixed. Thanks!
