### ISSUE TITLE
TONKeeper_баг с покупкой валюты

### ISSUE THREAD

**Issue by TONFOND** [tonkeeper/wallet#42]
### Bug Type

UX

### Reproduction steps

1. на главной странице нажать кнопку "Купить"
2. выбрать партнера по покупке
3. подтвердить покупку не имея достаточных средств на карте

https://user-images.githubusercontent.com/113825222/191137980-0670f600-4a1a-47b3-b061-24e5c94a5301.mov

[LOG_ошибки_2.docx](https://github.com/tonkeeper/wallet/files/9602934/LOG_._2.docx)

### Actual result

Давным давно я пытался купить TON через 1 из партнеров TONKeeper в приложении.
Оплата по каким-то причинам не смогла произойти.
Но транзакции на покупку до сих пор висят в статусе "в ожидании". При попытке зайти в транзакцию - выдается ошибка (лог приложен).

### Expected result

Транзакции должна иметь правильный статус, давать возможность провалится в нее и показать детали транзакции.

### Suggested Severity

Medium

### Device

Smartphone
- Device: Phone XS
- OS: iOS 15.2.1
- Browser APP Tonkeeper
- Version 2.6

**Comment by olyaMay** [comment]
Здравствуйте. Большое спасибо. Будем разбираться с проблемой. Баг заведен с внутренним номером TK-788

**Comment by olyaMay** [comment]
Здравствуйте. Подскажите, в новой версии приложения это все еще воспроизводится?
