### ISSUE TITLE
Not working camera and flashlight in QR scanner. Android 10.

### ISSUE THREAD

**Issue by Yauheni-Varenik** [tonkeeper/wallet#46]
### Bug Type

Functional

### Reproduction steps

1. Open Tonkeeper
2. Log in to your wallet
3. Click the QR scanner in the wallet 

![turn on](https://user-images.githubusercontent.com/90214308/191260514-acb3c9a3-4fe0-494a-a355-151406bf6dec.jpg) ![turn off](https://user-images.githubusercontent.com/90214308/191260536-401d7240-83be-45f3-b0ac-f671d6313eec.jpg) 

### Actual result

Not working camera and flashlight in QR scanner.

### Expected result

Camera and flashlight in QR scanner work.

### Suggested Severity

Medium

### Device

Smartphone:
- Device: Blackview BV9900Pro
- OS: Android 10
- Tonkeeper version 2.6
![allows](https://user-images.githubusercontent.com/90214308/191260885-9e6c2cbc-0c57-48e5-8078-e8e8c7f538ff.jpg)

### Additional Context

What cannot help;
1. Reboot
2. Reinstall app (after reinstall we also have one more bag with click the QR scanner in the wallet );
![error](https://user-images.githubusercontent.com/90214308/191261868-d3766d7d-c5e8-4ebf-94d5-2b35e81a01a4.jpg)

**Comment by olyaMay** [comment]
Hi. This issue is a duplicate. Please follow https://github.com/tonkeeper/wallet/issues/8 for updates. Thank you!
