### ISSUE TITLE
TONKeeper_баг с отправкой NFT

### ISSUE THREAD

**Issue by TONFOND** [tonkeeper/wallet#47]
### Bug Type

Functional

### Reproduction steps
1. выбрать NFT (ошибки возникали по NFT из коллекций GO TON Ticket и Cock Fights)
2. Нажать "Отправить NFT"
3. Ввести адрес кошелька
4. Нажать "Продолжить"
5. Подтвердить отправку и комиссию

https://user-images.githubusercontent.com/113825222/191341619-aa3a7712-9666-4b4b-a1e6-7b751cb0f61a.mov
<img width="1197" alt="Снимок экрана 2022-09-20 в 22 02 26" src="https://user-images.githubusercontent.com/113825222/191342850-d0eb9e7a-a9fe-4dab-bd67-06a84bfdb846.png">

### Actual result

При отправке отдельных NFT, NFT сначала отражается в отправленных, но спустя некоторое время опять отражается в списке NFT. 

### Expected result

NFT должна быть отправлена получателю

### Suggested Severity

High

### Device

Desktop (please complete the following information):
- OS: iOS 12.6
- Browser APP TONKeeper 
- Version 2.6

Smartphone (please complete the following information):
- Device: iPhone XS
- OS: iOS15.2.1
- Browser APP TONKeeper  
- Version 2.6

**Comment by olyaMay** [comment]
Hi, this issue is a duplicate of related #49 and #50. Thanks!
