### ISSUE TITLE
TONKeeper_баг с отражением суммы операции при отправке NFT

### ISSUE THREAD

**Issue by TONFOND** [tonkeeper/wallet#48]
### Bug Type

Functional

### Reproduction steps
1. выбрать NFT
2. Нажать "Отправить NFT"
3. Ввести адрес кошелька
4. Нажать "Продолжить"
5. Подтвердить отправку и комиссию

https://user-images.githubusercontent.com/113825222/191350185-52b6ed7d-eebc-4e2e-8e0d-9d5ce5f1e3c3.mov

<img width="1197" alt="Снимок экрана 2022-09-20 в 22 02 26" src="https://user-images.githubusercontent.com/113825222/191350637-ae4cbf40-1cd4-4698-b3e1-877e56cadea1.png">

### Actual result

При отправке некоторых NFT приложение показывает списание комиссии в размере 0,007360254TON по факту списывается сумма сумма 0,05TON+комиссия приложение это не отражает

### Expected result

Приложение должно отражать корректно все финансовые операции, которые происходят в моем кошельке

### Suggested Severity

High

### Device

Desktop (please complete the following information):

OS: iOS 12.6
Browser APP TONKeeper
Version 2.6
Smartphone (please complete the following information):

Device: iPhone XS
OS: iOS15.2.1
Browser APP TONKeeper
Version 2.6

**Comment by MariaBit** [comment]
Добрый день!
Более точное отображение списанных комиссий при взаимодействии с НФТ будет доступно в следующем релизе (внутренний номер задачи ТК-489).
Также можно посмотреть все транзакции и комиссии на https://tonapi.io/ в аккаунте своего кошелька.

Спасибо!
