### ISSUE TITLE
TONKeeper_Error, exit code 402

### ISSUE THREAD

**Issue by TONFOND** [tonkeeper/wallet#49]
### Bug Type

Functional

### Reproduction steps
1. выбрать NFT (ошибки возникали по NFT из коллекции Cock Fights)
2. Нажать "Отправить NFT"
3. Ввести адрес кошелька
4. Нажать "Продолжить"
5. Подтвердить отправку и комиссию

<img width="1197" alt="Снимок экрана 2022-09-20 в 22 49 33" src="https://user-images.githubusercontent.com/113825222/191351275-132bc239-08d4-4dbb-89e0-280e18392b40.png">

### Actual result

Пересекается с ошибкой https://github.com/tonkeeper/wallet/issues/47
На примере коллекции CockFights адрес смарт-контракта EQCQODJYOXt87QSbn-WzGyilGvQqdamhD_iOhyBx1jgYJhky

### Expected result

NFT должна быть отправлена получателю

### Suggested Severity

Critical

### Device

Desktop (please complete the following information):

OS: iOS 12.6
Browser APP TONKeeper
Version 2.6
Smartphone (please complete the following information):

Device: iPhone XS
OS: iOS15.2.1
Browser APP TONKeeper
Version 2.6

**Comment by voloshinskii** [comment]
Добрый день. Поддерживаем в рамках стандарта нфт https://github.com/ton-blockchain/TEPs/blob/master/text/0062-nft-standard.md
