### ISSUE TITLE
I don't get any notifications by app when i get TON on my wallet

### ISSUE THREAD

**Issue by Antohazp** [tonkeeper/wallet#5]
### Bug Type

Functional

### Reproduction steps

![photo_2022-09-16_20-58-02](https://user-images.githubusercontent.com/87418719/190659311-b70e2fee-352d-4e26-9982-b13b5459f32f.jpg)
![photo_2022-09-16_20-58-07](https://user-images.githubusercontent.com/87418719/190659337-4abe6102-a675-4f67-9e9f-21cee37ee61a.jpg)
I did some transfer to my wallet, but did not get any notifications on my phone. Before that i checked settings, they were on. Repeated that 2 times and same result - no notifications.

### Actual result

No notification

### Expected result

Notification on the phone about TON coins received.

### Suggested Severity

High

### Device

Smartphone :
- Device: [Xiaomi Redmi Note 7]
- OS: [Android 10 QKQ1.190910.002]

**Comment by olyaMay** [comment]
Hi. Does it reproduce now?

**Comment by Antohazp** [comment]
Hey. I reproduced, now i got notification when i received TON.

вт, 20 сент. 2022 г. в 03:01, omay ***@***.***>:
