### ISSUE TITLE
TONKeeper_Error, exit code 0

### ISSUE THREAD

**Issue by TONFOND** [tonkeeper/wallet#50]
### Bug Type

Functional

### Reproduction steps
1. выбрать NFT (ошибки возникали по NFT из коллекций GO TON Ticket)
2. Нажать "Отправить NFT"
3. Ввести адрес кошелька
4. Нажать "Продолжить"
5. Подтвердить отправку и комиссию

<img width="1197" alt="Снимок экрана 2022-09-20 в 22 57 11" src="https://user-images.githubusercontent.com/113825222/191352591-b7f57cb4-cae1-4b39-8b87-b89dca39161e.png">

### Actual result

Пересекается с [ошибкой 47](https://github.com/tonkeeper/wallet/issues/47)
На примере коллекции GO TON ticket адрес смарт-контракта EQBpripk7AcVMIsoKUiUpvdrP2nErLaRtFIWhQ6qMNW0ShRJ
С данной ошибкой еще хуже чем с [предыдущей](https://github.com/tonkeeper/wallet/issues/49),
так как списывается и комиссия и стоимость перевода NFT 0,05TON
Так, имея 3 безуспешные попытки "выбросить", отправить в cryptoblackhole.ton билет на мероприятие я стал беднее на 0,15TON + расходы по комиссии.
Любопытная получается NFT (билет) сколько его не выбрасывай - он крипту отправляет в чью-то кубышку, а билет все равно остается с тобой ((

### Expected result

NFT должна быть отправлена получателю

### Suggested Severity

Critical

### Device

Desktop (please complete the following information):

OS: iOS 12.6
Browser APP TONKeeper
Version 2.6
Smartphone (please complete the following information):

Device: iPhone XS
OS: iOS15.2.1
Browser APP TONKeeper
Version 2.6

**Comment by olyaMay** [comment]
Hi, this issue is a duplicate. Please follow https://github.com/tonkeeper/wallet/issues/15 for updates. Thanks!

**Comment by TONFOND** [comment]
Ok, thanks, but the Suggested Severit should be critical, as the user's funds are debited.
