### ISSUE TITLE
NFT button appeared if condition is met

### ISSUE THREAD

**Issue by isopen** [tonkeeper/wallet#51]
### Bug Type

UX

### Reproduction steps

![Снимок экрана от 2022-09-21 03-27-13](https://user-images.githubusercontent.com/7373292/191357920-ea2202d0-c024-4e4e-9b13-15d81aa8e36b.png)

### Actual result

No NFT on balance. There is a NFT button.
<img src="https://user-images.githubusercontent.com/7373292/191358711-fa0b11bd-68c9-479f-92bc-6939b45fad4d.png" width="25%" />
You can check at: EQADXaOqEmIzxvJBN9oQeaNYEA9Q5EBIYxQUYF7uM6InWJCr

![image](https://user-images.githubusercontent.com/7373292/191365122-d85c5c82-dd7a-4e46-96a0-9542704e1aa9.png)

### Expected result

According to the conditions from olyaMay, there should not be a NFT button
Related report: https://github.com/tonkeeper/wallet/issues/28

### Suggested Severity

Critical

### Device

Desktop (please complete the following information):
- OS: Android 12
- Browser Tonkeeper
- Version 2.6

**Comment by MariaBit** [comment]
Hi, thanks for letting us know about this inconsistency. We are looking into this issue.

**Comment by MariaBit** [comment]
The issue will be fixed in the next release. 
NFT tab will be visible only when there is NFT on wallet balance, as it worked before. So I'm closing the issue.

**Comment by isopen** [comment]
Please tell me TK-Number

**Comment by MariaBit** [comment]
TK-779

**Comment by isopen** [comment]
Thanks
