### ISSUE TITLE
TONKeeper_Error, exit code 766 RED Coin

### ISSUE THREAD

**Issue by TONFOND** [tonkeeper/wallet#52]
### Bug Type

Functional

### Reproduction steps
1. перейти во вкладку RED Coin
2. нажать "Отправить"
3. ввести адрес кошелька и подтвердить отправку

<img width="1197" alt="Снимок экрана 2022-09-20 в 23 30 39" src="https://user-images.githubusercontent.com/113825222/191359859-c582ffc5-f214-403c-a546-58bf3f888be3.png">

### Actual result

При отправке RED Coin на другой кошелек приложение позволило произвести отправку, но на кошелек получателя RED Coin не попали, а были возвращены, видимо, на кошелек отправителя. Результат - потеря комиссий.
В моем понимании любая недоработка ПО, которая не позволяет пользователю совершить целевое действие, а приводит к потере пользователем активов (даже в виде комиссий), является критической.
Если функционал с RED Coin пока не реализован, давайте и не будем позволять пользователям отправлять их друг другу. Напишите системное сообщение о недоступности отправки в настоящее время и продолжайте развивать свое ПО.

### Expected result

Перевод RED Coin на другой кошелек или ограничение в данном действии.

### Suggested Severity

Critical

### Device

Desktop (please complete the following information):

OS: iOS 12.6
Browser APP TONKeeper
Version 2.6
Smartphone (please complete the following information):

Device: iPhone XS
OS: iOS15.2.1
Browser APP TONKeeper
Version 2.6

**Comment by olyaMay** [comment]
Здравствуйте. Насколько я знаю, на REDCOIN при выпуске был установлен lock-up на 4 месяца и сейчас совершать с ним какие-либо действия невозможно. Со своей стороны мы не можем отслеживать все условия всех созданных смарт-контрактов, но постараемся совершенствоваться над этим в дальнейшем.

**Comment by TONFOND** [comment]
да, желательно чтобы функционал приложения соответствовал функционалу смартконтрактов токенов доступных через приложение

**Comment by voloshinskii** [comment]
@TONFOND добрый день. Функционал соответствует стандарту жеттонов. Локап не был включен в стандарт, а поддерживать 100 и 1 реализацию локапов разными командами токенов тонкипер точно не смог бы, даже при всём желании. В идеале разработчикам стоило протащить сначала локапы в стандарт и только после этого делать своё решение
