### ISSUE TITLE
When putting on sell NFT and scanning QR code by Tonkeeper, "An error occured" appears if not enough funds for Fee

### ISSUE THREAD

**Issue by julialips** [tonkeeper/wallet#54]
### Bug Type

Functional

### Reproduction steps

1. Open Tonkeeper
2. Log in to an account with small amount of TONs
3. Create NFT on https://getgems.io
4. Put your NFT on sale, choose 'Fixed price' option. Fill the price field -> QR code appears
5. Scan the QR using Tonkeeper scanner 
  

### Actual result

"An error occured" red text appears.
![image](https://user-images.githubusercontent.com/45575431/191619580-386c4647-c8dd-41fb-be2c-a9d2371cacaa.png)

### Expected result

Handle the error, and write corresponding text, that a user have not enough balance to pay the Fee

### Suggested Severity

Low

### Device

- Device: iPhone 11
- OS: 14.3

**Comment by olyaMay** [comment]
Fixed.
