### ISSUE TITLE
When putting on sell NFT, transaction history is not displayed the amount being sent 

### ISSUE THREAD

**Issue by julialips** [tonkeeper/wallet#55]
### Bug Type

Functional

### Reproduction steps

1.Open Tonkeeper
2. Log in to an account with positive TON balance
3. Create NFT on https://getgems.io/
4. Put your NFT on sale, choose 'Fixed price' option. Fill the price field -> QR code appears
5. Scan the QR using Tonkeeper scanner
6. Click "Confirm" button at the bottom sheet  

### Actual result

After a while, we see 3 transaction in history.
One of them is "NFT" instead of showing sent amount

![image](https://user-images.githubusercontent.com/45575431/191621467-22a48b36-016e-42db-9b7b-5d12f54bb718.png)

### Expected result

If I open Tonhub app, I will see that this transaction cost some funds, which I can't see using Tonkeeper

![image](https://user-images.githubusercontent.com/45575431/191621404-207882e5-82f5-4285-b04a-82924dfa444a.png)

### Suggested Severity

Medium

### Device

- Device: iPhone 11
- OS: 14.3

**Comment by MariaBit** [comment]
Hi, Tonkeeper wallet will show more detailed history in the next release.
Thanks!
