### ISSUE TITLE
When putting on sell NFT and scanning QR code by wrong wallet, Fee will be withdrawn

### ISSUE THREAD

**Issue by julialips** [tonkeeper/wallet#56]
### Bug Type

Functional

### Reproduction steps

Precondition: You have 2 wallets
1. Open Tonkeeper
2. Log in to an account A
3. Create NFT on https://getgems.io/ using account A
4. Put your NFT on sale, choose 'Fixed price' option. Fill the price field -> QR code appears
5. Scan the QR using Tonkeeper scanner on account B 
6. Bottom sheet appear, confirm it

### Actual result

The transaction is completed and displayed in history, the commission has been withdrawn

### Expected result

When scanning a QR, there may be a check for right wallet. 
To protect users waste their funds for commissions

### Suggested Severity

Medium

### Device

Smartphone:
- Device: iPhone 11
- OS: 14.3

**Comment by MariaBit** [comment]
Hi, the issue has been registered in our system with internal # ТК-777.
You will get a PR number when it will be fixed. Thanks!

**Comment by MariaBit** [comment]
The issue has been fixed - PR #179
