### ISSUE TITLE
Impossible to remove NTF  from sale if enough funds 

### ISSUE THREAD

**Issue by julialips** [tonkeeper/wallet#57]
### Bug Type

Functional

### Reproduction steps

Precondition: you have an account with NFT on sale
1. Open Tonkeeper app
2. Log in to an account from precondition with positive TON balance
3. Remove your NFT from sale https://getgems.io/  -> QR code appears
5. Scan the QR using Tonkeeper scanner in your account -> bottom sheet appear with NFT info
6. Confirm the transaction in bottom sheet 

### Actual result

"An error occured" error appears.

### Expected result

Impossible to remove NFT. 
Because I have enough funds (1 TON for gas fees and 0.005 as I see required fee in Tonkeeper).
May be there are some more fees, but I do not see it. Also the error do not helps to understand. 

https://user-images.githubusercontent.com/45575431/191820268-c3e5c52f-cd10-47a0-b8f2-a481c3afe62a.MP4

![image](https://user-images.githubusercontent.com/45575431/191820353-fb5c30a4-724f-4d0b-b439-70dac1937cbd.png)
![image](https://user-images.githubusercontent.com/45575431/191820546-b798a51f-859a-44a0-8eac-6530083991a9.png)
![image](https://user-images.githubusercontent.com/45575431/191820810-54f17829-f2b1-4c94-8467-1f4cdbe6fba4.png)

### Suggested Severity

High

### Device

- Device: iPhone 11
- OS: 14.3

**Comment by olyaMay** [comment]
Hi. For successful interaction with NFT you balance should be around 1.5 TON
