### ISSUE TITLE
Subscription not charged

### ISSUE THREAD

**Issue by maxuver** [tonkeeper/wallet#58]
### Bug Type

Functional

### Reproduction steps

1. Go to the subscriptions section of my wallet 
2. See, that the subscription price is 1 TON and the payment date is September 21
3.  Go back to main wallet
4. See that at the time of September 20, the wallet had enough balance for payment
5. Check today date - September 23 

https://user-images.githubusercontent.com/78837452/191893276-4e5f5a54-b7de-42ca-aa21-f9cd43692853.mp4

### Actual result

Subscription to this community for old subscribers costs 1 TON. I am an old subscriber and have successfully paid 1 TON for this closed channel all months before. For new subscribers the charge is 3 TON. 

### Expected result

The subscription was to be paid in accordance with the specified price of 1 TON

### Suggested Severity

High

### Device

Device: Apple iPhone 11
OS: iOS 15.6.1
App Version 2.6

**Comment by olyaMay** [comment]
Hi. We need more information about you subscription to solve your problem.
Can you please give us your wallet address and community url?

**Comment by maxuver** [comment]
Community URL: https://t.me/+F1SJuPxTjdFlOTBi
Address: EQCX0M7_pQrL7e2jnVYZnXWpJzCK_Z4ryYCWU1qT9I6jdIas

**Comment by maxuver** [comment]
@olyaMay

**Comment by olyaMay** [comment]
Sorry for long answer. You should contact @donate support
