### ISSUE TITLE
Unable to buy Premium in Web app. Unknown protocol version: undefined

### ISSUE THREAD

**Issue by Thoufak** [tonkeeper/wallet#595]
### Bug Type

Functional

### Reproduction steps

1. Go to https://wallet.tonkeeper.com/ and log in to your wallet.
2. Go to https://fragment.com/premium and connect your wallet using QR code.
3. Enter a username and click "Gift Telegram Premium".
4. Scan the given QR code.

### Actual result

The QR code scanner closes, but the purchase is not made and I see an alert: "Unknown protocol version: undefined".

<img width="686" alt="image" src="https://github.com/tonkeeper/wallet/assets/40132582/d75b6529-077b-4b32-9de4-1344d389ac12">

### Expected result

The purchase is made.

### Suggested Severity

High

### Device

- OS: MacOS
- Browser: Chrome
- Version: 117.0.5938.149 (Official Build) (arm64)

### Additional Context

The QR code that I used:

![IMG_6917](https://github.com/tonkeeper/wallet/assets/40132582/b586d323-5190-45aa-b594-0d3d309a3664)

Also, at the same moment the alert shows, there's this log in the browser console:
```
Error: unknown operator https://app.tonkeeper.com/v1/txrequest-url/fragment.com/tonkeeper/rawRequest
    at s (main.9f395c1a.js:2:1077603)
    at main.9f395c1a.js:2:1423628
    at h (main.9f395c1a.js:2:2478981)
    at Generator.<anonymous> (main.9f395c1a.js:2:2480333)
    at Generator.next (main.9f395c1a.js:2:2479410)
    at r (main.9f395c1a.js:2:2471234)
    at s (main.9f395c1a.js:2:2471437)
    at main.9f395c1a.js:2:2471496
    at new Promise (<anonymous>)
    at Object.<anonymous> (main.9f395c1a.js:2:2471377)
```

**Comment by MariaBit** [comment]
Hello!
https://wallet.tonkeeper.com/ only supports connecting to dApps that use Ton Connect v2.
Connecting to dApps that do not support Ton Connect v2 is currently not possible.
For example, https://fragment.com/premium uses Ton Connect v1.
