### ISSUE TITLE
TONKeeper_ Error exit code 407

### ISSUE THREAD

**Issue by TONFOND** [tonkeeper/wallet#61]
### Bug Type

Functional

### Reproduction steps

1. Входим в кошелёк
2. Нажимаем «Отправить». Кошелёк адресата - аукционный-кошелёк для покупки домена
3. Указываем сумму платежа, нажимаем  отправить
4. Платёж не подтверждается, указывается ошибка Error, exit code 407
5. Деньги возвращаются на кошелёк 
Info оплата производилась с кошелька v4R1

### Actual result

1. Платёж не подтверждается, указывается ошибка Error, exit code 407
2. Деньги возвращаются на кошелёк 

### Expected result

1. Платёж прошёл

### Suggested Severity

Critical

### Device

Smartphone (please complete the following information):
- Device: IPhone XS
- OS: 15.7
- Browser APP TONKeeper
- Version 2.6

### Additional Context

![3E0D11FB-0999-45A9-AD4D-F0B1E7C8C8F0](https://user-images.githubusercontent.com/113825222/191951584-d560b34a-f507-40dd-aa98-47be110a9c64.png)

**Comment by olyaMay** [comment]
Здравствуйте. Контракт v4r1 работает некорректно. Рекомендую перевести средства на v4r2 и пользоваться им.

**Comment by TONFOND** [comment]
Только v4r2 работает корректно?
А 3 версии кошельков тоже лагают?

**Comment by olyaMay** [comment]
v3r2 так же стабильно работает. Различие между v3r2 и v4r2 в том, что у последнего доступны подписки.

**Comment by TONFOND** [comment]
Thx
