### ISSUE TITLE
TONKeeper_не доступен ввод через клавиатуру в приложении

### ISSUE THREAD

**Issue by TONFOND** [tonkeeper/wallet#64]
### Bug Type

UX

### Reproduction steps

1. вход в приложение через PIN
2. при попытке ввода кода с клавиатуры, приложение не реагирует
3. получилось войти только через ввод PIN мышкой

### Actual result

при попытке ввода кода с клавиатуры, приложение не реагирует

### Expected result

приложение должно позволять ввести PIN-код через клавиатуру

### Suggested Severity

Low

### Device

Desktop (please complete the following information):

OS: iOS 12.6
Browser APP TONKeeper
Version 2.6

### Additional Context

https://user-images.githubusercontent.com/113825222/192119344-fed9c003-e5ea-4af0-9180-8441f4f083da.mov

**Comment by olyaMay** [comment]
Здравствуйте. Подскажите, речь идет о приложении загруженном из апстора на макбук м1?

**Comment by TONFOND** [comment]
да, только на M2

**Comment by olyaMay** [comment]
Изначально приложение написано для смартфонов, возможность запустить приложение на макбуке - фича от эпла. Соответственно на смартфонах не поднимается клавиатура при вводе пин кода, поэтому с клавиатуры ноутбука не получится его ввести. Если это неудобно - могу предложить включить в настройках вход по touch id, он работает. Спасибо!

**Comment by TONFOND** [comment]
Спасибо за ответ!
В любом случае тонкипер пока лучший кошелёк, и чтобы оставаться таким нужно обращать внимание и на детали ;)
