### ISSUE TITLE
Неверная информация о транзакции.

### ISSUE THREAD

**Issue by HyperboreanGroyper** [tonkeeper/wallet#65]
### Bug Type

Other

### Reproduction steps

1. Производим смену владельца нфт НЕ через приложение tonkeeper.
2. С транзакцией передаём нфт количество TON, которого не хватает для смены владельца.

![image](https://user-images.githubusercontent.com/113979537/192150892-a6f0e25b-a2a2-4e50-8d91-7b5710964fc6.png)
![image](https://user-images.githubusercontent.com/113979537/192150893-57ab5f0c-7cd1-4fff-903c-05519db629d3.png)
![image](https://user-images.githubusercontent.com/113979537/192150897-ed2f666a-cd4f-43d8-b4b1-60e555cc79b9.png)

### Actual result

Получаем информацию о возвращении TON за вычетом комиссий и сообщение об успешной отправке НФТ.

### Expected result

Вместо сообщения об отправке, сообщение с ошибкой.

### Suggested Severity

Low

### Device

Desktop (please complete the following information):
- OS: windows10
- Browser chrome
- Version 105.0.5195.127

Smartphone (please complete the following information):
- Device: honor FRD-L09
- OS: iOS7.0
- Android app
- Version  2.6

**Comment by MariaBit** [comment]
Добрый день! 
Уточните, пожалуйста, каким образом вы меняете  владельца НФТ "НЕ через приложение tonkeeper"?
Будет идеально, если вы сможете добавить видео, на котором будут видны все шаги воспроизведения.
Заранее спасибо!

**Comment by MariaBit** [comment]
Закрываю задачу, так как не получила ответ. Без деталей мы не можем проанализировать и разобраться, что произошло в описанном случае.
