### ISSUE TITLE
Native iOS app is crashing on jailbroken device after last update

### ISSUE THREAD

**Issue by ExxRyan** [tonkeeper/wallet#680]
### Bug Type

Other

### Reproduction steps

1. Install uncover jailbreak on IPhone 11
2. Install Tonkeeper
3. Launch Tonkeeper
4. It should crash

### Actual result

Working Tonkeeper app

### Expected result

Crashing on loading screen

### Suggested Severity

Low

### Device

Smartphone (please complete the following information):
- Device: iPhone 11
- OS: iOS 14.7.1
- Browser: Native App
- Version: undefined

### Additional Context

device was jailbreaked

**Comment by olyaMay** [comment]
Hi. We cant guarantee that application will work with jailbreaked devices
