### ISSUE TITLE
Expensive TX via ton keeper wallet

### ISSUE THREAD

**Issue by gades** [tonkeeper/wallet#695]
### Bug Type

Other

### Reproduction steps

1. Goto swap jettons in tonkeeper 
2. swap ton to jetton
3. Go to ston.fi 
4. swap same ton to jetton
5. compare TX fees and tx via ton keeper 2x time expensive

### Actual result

TX via ton keeper 2x times expensive than on ston.fi

0,096369964 TON - via Ston.fi
![IMG_1155](https://github.com/tonkeeper/wallet/assets/4200730/f4ab3d7f-5c13-4b3d-903e-8e5dd9eb12a1)
0,213115012 TON - via Tonkeper
![IMG_1156](https://github.com/tonkeeper/wallet/assets/4200730/206ee906-8cb4-425c-ab3b-e37cb5bfa0fd)

### Expected result

I'm expecting  almost same result but not 2 times expensive

### Suggested Severity

High

### Device

Smartphone (please complete the following information):
- Device: iPhone 12 Pro max
- OS: 17.3
- Version 3.6

**Comment by olyaMay** [comment]
Hi. Additional fee is charged through the smart contract, we will consider the issue to find possible solution
