### ISSUE TITLE
Invalid link in testnet

### ISSUE THREAD

**Issue by teplulya** [tonkeeper/wallet#71]
### Bug Type

Other

### Reproduction steps

Переключаюсь на тестнет-версию
1. Приобретаю тестовую NFT
2. Открываю её во вкладке NFT
3. Нажимаю "Подробнее"

### Actual result

Попадаю на прод https://tonscan.org

### Expected result

Должна была попасть на тестовую версию https://testnet.tonscan.org/

### Suggested Severity

Medium

### Device

Smartphone
Device: iPhone 13 mini
OS: iOS 15.6
Browser: safari

**Comment by olyaMay** [comment]
Hi, the issue has been registered in our system with internal ТК-787.
You will get a PR number when it will be fixed. Thanks!

**Comment by olyaMay** [comment]
Здравствуйте. Баг был исправлен, работающая версия будет доступна пользователям в ближайшем релизе.
