### ISSUE TITLE
"Использовать распознавание лица" in section "Безопасность" should be replaced by "Использовать биометрию"

### ISSUE THREAD

**Issue by bakirov** [tonkeeper/wallet#74]
"Использовать распознавание лица" in section "Безопасность" should be replaced by "Использовать биометрию", because it is what it does: on my android phone this option allows me to use a fingerprint scanner.

**Comment by MariaBit** [comment]
Hi, this feature has been registered with internal #TK-573. You will get a PR number when it will be fixed. Thanks!
