### ISSUE TITLE
Chrome Extensions : Can not send a transaction when the fee calculation fails

### ISSUE THREAD

**Issue by donguks** [tonkeeper/wallet#742]
### Bug Type

Functional

### Reproduction steps

Send a transaction with Tokeeper browser extension. The message size of the transaction might be large enough that the tonekeeper might not be able to calculate the fee.

### Actual result

When it failed to calculate fee, I cannot click "Confirm"

<img width="381" alt="스크린샷 2024-02-22 오후 3 43 01" src="https://github.com/tonkeeper/wallet/assets/69144981/888fb5fe-1f66-4a97-86b0-78e51b3beea0">

### Expected result

User can send "Confirm" even if the fee calculation fails. 
I can send transaction with Tonkeeper mobile app in same environments.

### Suggested Severity

Low

### Device

Desktop (please complete the following information):
- OS: MacOS 14.2.1
- Browser Chrome
- Version v3.6.2

**Comment by feederndt** [comment]
I don't use Mac but on my Window PC I solve this error by using sync my clock. Hopefuly you will find this feature in your OS and solve your problem
![image](https://github.com/tonkeeper/wallet/assets/90165242/5537635a-018b-40fe-be3f-8b6a5b1fb20c)

**Comment by olyaMay** [comment]
Hi. This repository is about mobile application. You can report web problems here: https://github.com/tonkeeper/tonkeeper-web
