### ISSUE TITLE
-NaN TON (stacking from tonkeeper) #1

### ISSUE THREAD

**Issue by isopen** [tonkeeper/wallet#79]
### Bug Type

UI/UX

### Reproduction steps

<img src='https://user-images.githubusercontent.com/7373292/194775461-2fb37f7f-d658-4e79-bfe3-4d0623d20772.png' width='30%' />

0. Address for test: EQADXaOqEmIzxvJBN9oQeaNYEA9Q5EBIYxQUYF7uM6InWJCr
1. Copy the address of the nominator from the website via Android from page
https://tonwhales.com/staking/pool/EQCY4M6TZYnOMnGBQlqi_nyeaIB1LeBFfGgP4uXQ1VWhales
3. Send TON for staking (the case when the transaction will be processed longer)
4. -NaN TON + automatically changed transaction history in tonkeeper

Alias: https://github.com/ton-blockchain/bug-bounty/issues/1

### Actual result

-NaN TON + automatically changed transaction history in tonkeeper

### Expected result

1. -1000 TON
2. History matches history on tonscan

### Suggested Severity

Critical

### Device

Android 12
Samsung A71
Tonkeeper 2.6.1
Google Chrome Mobile

**Comment by olyaMay** [comment]
Здравствуйте. Действительно была проблема с отправкой крупных сумм, должно быть исправлено в текущем релизе (2.7 - 2.7.1).

**Comment by isopen** [comment]
@olyaMay Most likely, the ticket label in this case should correspond to the bug, but in this case you know better and you marked the ticket as a question. It's not a mistake?

**Comment by isopen** [comment]
@olyaMay I'll check it out with pleasure, but I can't update to the latest version tonkeeper right now...
See more...Please...

https://user-images.githubusercontent.com/7373292/195961427-8532d61b-32ec-48d9-a186-800794e02281.mp4

**Comment by isopen** [comment]
@olyaMay I'll check it out with pleasure, but I can't update to the latest version tonkeeper right now...
See more...Please...

https://user-images.githubusercontent.com/7373292/195961427-8532d61b-32ec-48d9-a186-800794e02281.mp4

**Comment by olyaMay** [comment]
А может быть такое, что приложение вы изначально ставили при помощи apk с сайта, а не через плей маркет?
