### ISSUE TITLE
Support Ledger Wallet

### ISSUE THREAD

**Issue by RandomUsernome** [tonkeeper/wallet#805]
Wallets such as TonHUB and MyTonWallet have already added support for Ledger's Hardware Wallet, but TonKeeper, which is the best of all to date, has not implemented this yet, I hope they add support to this so that we have the possibility of having our 100% Offline TONs managed by TonKeeper.

More details of what should be needed can be found on the website:
https://developers.ledger.com/

**Comment by sorokin0andrey** [comment]
Done in #835

Will be in the next build

**Comment by RandomUsernome** [comment]
Hello, first of all I would like to thank you immensely for listening to my suggestion and adding support for Ledger Wallet, but unfortunately you seem to have removed a very useful and important feature that is to switch between versions of TON, I have a wallet in an old version of TON Wallet, and I can't connect it because now only the new versions appear with no option to switch or something similar. Would it be possible to bring this feature back? Was there any reason to remove it? I can't find any wallet with Ledger Wallet support that supports the old versions of TON Wallet, only you had this feature and were my hope.
Em 12 de mai. de 2024, 10:32 -0300, Andrey Sorokin ***@***.***>, escreveu:
