### ISSUE TITLE
Missing App icon (Android 7.0)

### ISSUE THREAD

**Issue by Sami32** [tonkeeper/wallet#886]
### Bug Type

UX

### Reproduction steps

Install TONkeeper on Android 7.0.
App doesn't show it's own icon.

### Actual result

No App own icon

### Expected result

App show it's own icon.

### Suggested Severity

Low

### Device

Smartphone (please complete the following information):
- Device: Xiaomi Redmi Note 4
- OS: Google Android 7.0
- Version: 4.6.2
![IMG_20240604_233145](https://github.com/tonkeeper/wallet/assets/18471069/e59706b9-6e4b-4d40-ad28-5e1ec42b831f)

**Comment by olyaMay** [comment]
Hi. This is an old android version.
