### ISSUE TITLE
Invalid Seed phrase

### ISSUE THREAD

**Issue by octapudus** [tonkeeper/wallet#888]
### Bug Type

Security / seed phrase not accepted:

### Reproduction steps

I can't add my seed phrase in tonKeper which was generated by Ledger

The problem is that I moved my NFT numbers on the seed phrase that was generated and managed by Ledger and I can not move them anymore with Ledger + moreover as an extra issue I can not insert my seed phrase into the tonkeeper.

I am inserting my seed phrase generated by Ledger in 2021. It says error "invalid seed phrase".

Why is the seed phrase generated with TonKeper different from one generated by metamask/phantom and others?
Why did you activate the function "pair with ledger" that would lead people to these situations?

Why Tonkeper does not accept seed phrases securely generated by ledger?

I can't use my NFT numbers.
it's frustrating!

### Actual result

"invalid seed phrase".

### Expected result

The seed phrase should work and get accepted by TonKeper

### Suggested Severity

Vulnerability

### Device

Desktop (please complete the following information):
- OS: macos
- Browser chrome
- Version latest

Smartphone (please complete the following information):
- Device: iphone
- OS: latest

**Comment by olyaMay** [comment]
Hi. Ledger now doesn't support operations with NFT and TonConnect. We are waiting for updates from them.
