### ISSUE TITLE
The cost is not displayed when trying to attach a domain

### ISSUE THREAD

**Issue by isopen** [tonkeeper/wallet#96]
### Bug Type

UI/UX

### Reproduction steps

1. Choose domain
2. Participate in the TON DNS auction
3. Wait for the auction to end
4. Try to attach a domain to an address
5. Binding  price not showing in Tonkeeper (result: transaction -0.05 TON)
<img src='https://user-images.githubusercontent.com/7373292/195975630-6451621a-181b-4463-a7c0-ddfc0afd9d02.png' width='30%' />

### Actual result

Binding price not showing in Tonkeeper

### Expected result

Binding price showing in Tonkeeper

### Suggested Severity

High

### Device

Smartphone (please complete the following information):
- Device: Samsung A71
- OS: Android 12
- Browser Tonkeeper
- Version 2.6.1

**Comment by olyaMay** [comment]
Hi, the issue have been registered in our system with internal TK-881. You will get a PR number when it will be fixed. Thanks!

**Comment by olyaMay** [comment]
Issue was fixed in 3.4.4 release.
